modLoader="javafml"
loaderVersion="[40,)"
license="GNU AGPLv3"
issueTrackerURL="https://github.com/Nyphet/just-vertical-slabs/issues" #optional
[[mods]]
modId="justverticalslabs"
version="3.2.0.3"
displayName="Just Vertical Slabs"
updateJSONURL="https://raw.githubusercontent.com/Nyphet/just-vertical-slabs/master/forge/updates.json" #optional
displayURL="https://github.com/Nyphet/just-vertical-slabs" #optional
logoFile="just-vertical-slabs.gif" #optional
# A text field displayed in the mod UI
credits="A very big thank you goes to the Forge team that allowed anyone to mod Minecraft for free and their support in the Forge Forums.\nIn particular I want to thank diesieben07 that followed me throughtout most of the development, without him none of this would have been possible." #optional
authors="Crystal Spider" #optional
description="Finally build with Vertical Slabs in Vanilla or with any mod you've installed!"
[[dependencies.justverticalslabs]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justverticalslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
#optional
