modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Nyphet/just-vertical-slabs/issues" #optional
[[mods]]
modId="justverticalslabs"
version="${file.jarVersion}"
displayName="Harvest with ease"
updateJSONURL="https://raw.githubusercontent.com/Nyphet/just-vertical-slabs/master/updates.json" #optional
displayURL="https://github.com/Nyphet/just-vertical-slabs" #optional
logoFile="just-vertical-slabs.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
authors="Crystal Spider" #optional
description='''
Harvest your crops with ease by simply right clicking on them, without having to tediously destroy and replant them all the time!

This mod by defaults supports all Minecraft Vanilla crops (wheat, potatoes, carrots and beetroots) plus nether warts and cocoa beans.
It also supports any modded crop extending the CropBlock class.
Pumpkins, melons, cacti and sugar canes are not included by design as they are more blockish and do not require to destroy the whole plant and replant it again to be harvested.
For any modded crop that doesn't work out of the box with this mod, a configuration file is provided where their IDs can be added to (at least theoretically) make them compatible.
'''
[[dependencies.justverticalslabs]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justverticalslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
#optional
