modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Nyphet/just-vertical-slabs/issues" #optional
[[mods]]
modId="justverticalslabs"
version="${file.jarVersion}"
displayName="Just Vertical Slabs"
updateJSONURL="https://raw.githubusercontent.com/Nyphet/just-vertical-slabs/master/updates.json" #optional
displayURL="https://github.com/Nyphet/just-vertical-slabs" #optional
logoFile="just-vertical-slabs.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
authors="Crystal Spider" #optional
description='''
'''
[[dependencies.justverticalslabs]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.justverticalslabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
#optional
